<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Company;
use App\Models\DashboardContent;

class CompanySeeder extends Seeder
{
    public function run(): void
    {
        $companies = [
            [
                'name' => 'Blue Ocean Consulting',
                'slug' => 'blue-ocean-consulting',
                'logo' => null,
                'category' => 'Consulting',
                'website_link' => 'https://blueocean.com',
                'short_description' => 'Business strategy and management consulting.',
                'full_description' => 'Blue Ocean Consulting provides expert business strategy, management, and digital transformation services for enterprises worldwide.',
                'banner' => null,
                'comp_plan_link' => null,
                'signup_link' => null,
                'backoffice_link' => null,
                'intro_video_link' => null,
                'webinar_link' => null,
                'location' => 'New York, USA',
                'phone' => '+1 212-555-0100',
                'tagline' => 'Navigate Your Future',
                'ceo_name' => 'Jane Smith',
                'theme_id' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'GreenTech Innovations',
                'slug' => 'greentech-innovations',
                'logo' => null,
                'category' => 'Technology',
                'website_link' => 'https://greentech.com',
                'short_description' => 'Eco-friendly technology solutions.',
                'full_description' => 'GreenTech Innovations develops sustainable technology products for a cleaner planet.',
                'banner' => null,
                'comp_plan_link' => null,
                'signup_link' => null,
                'backoffice_link' => null,
                'intro_video_link' => null,
                'webinar_link' => null,
                'location' => 'San Francisco, USA',
                'phone' => '+1 415-555-0200',
                'tagline' => 'Innovate Green',
                'ceo_name' => 'John Doe',
                'theme_id' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Legal Eagle Partners',
                'slug' => 'legal-eagle-partners',
                'logo' => null,
                'category' => 'Legal',
                'website_link' => 'https://legaleagle.com',
                'short_description' => 'Corporate and civil law specialists.',
                'full_description' => 'Legal Eagle Partners offers legal services for businesses and individuals, specializing in corporate and civil law.',
                'banner' => null,
                'comp_plan_link' => null,
                'signup_link' => null,
                'backoffice_link' => null,
                'intro_video_link' => null,
                'webinar_link' => null,
                'location' => 'London, UK',
                'phone' => '+44 20 7946 0958',
                'tagline' => 'Justice Delivered',
                'ceo_name' => 'Emily Clark',
                'theme_id' => 8,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MediCare Solutions',
                'slug' => 'medicare-solutions',
                'logo' => null,
                'category' => 'Healthcare',
                'website_link' => 'https://medicaresolutions.com',
                'short_description' => 'Healthcare management and consulting.',
                'full_description' => 'MediCare Solutions provides healthcare management, consulting, and digital health services for clinics and hospitals.',
                'banner' => null,
                'comp_plan_link' => null,
                'signup_link' => null,
                'backoffice_link' => null,
                'intro_video_link' => null,
                'webinar_link' => null,
                'location' => 'Toronto, Canada',
                'phone' => '+1 416-555-0300',
                'tagline' => 'Care Beyond Boundaries',
                'ceo_name' => 'Dr. Alan Grant',
                'theme_id' => 9,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'EduSmart Academy',
                'slug' => 'edusmart-academy',
                'logo' => null,
                'category' => 'Education',
                'website_link' => 'https://edusmart.com',
                'short_description' => 'Online and in-person education.',
                'full_description' => 'EduSmart Academy delivers online and in-person education for students and professionals worldwide.',
                'banner' => null,
                'comp_plan_link' => null,
                'signup_link' => null,
                'backoffice_link' => null,
                'intro_video_link' => null,
                'webinar_link' => null,
                'location' => 'Sydney, Australia',
                'phone' => '+61 2 5550 4000',
                'tagline' => 'Learn. Grow. Succeed.',
                'ceo_name' => 'Sophie Lee',
                'theme_id' => 10,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'AutoDrive Motors',
                'slug' => 'autodrive-motors',
                'logo' => null,
                'category' => 'Automotive',
                'website_link' => 'https://autodrive.com',
                'short_description' => 'Automotive sales and services.',
                'full_description' => 'AutoDrive Motors is a leader in automotive sales, services, and aftercare for a global clientele.',
                'banner' => null,
                'comp_plan_link' => null,
                'signup_link' => null,
                'backoffice_link' => null,
                'intro_video_link' => null,
                'webinar_link' => null,
                'location' => 'Berlin, Germany',
                'phone' => '+49 30 5550 6000',
                'tagline' => 'Drive Your Dream',
                'ceo_name' => 'Max Müller',
                'theme_id' => 17,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        \DB::table('companies')->insert($companies);
    }
}
